url: http://freesoft-al.github.io
baseurl: /bright-electrical-specialists-ltd/

# Site settings
title: Bright Electrical Specialists Ltd
email: ilirraci@yahoo.co.uk
phone: +12 34567890
description: "Write an awesome description for your new site here. You
can edit this line in _config.yml. It will appear in your document
head meta (for Google search results) and in your feed.xml site
description."

# Color settings
color:
  primary: 0088ff
  secondary: 66eeff
  secondary-dark: 888888

# Build settings
markdown: kramdown
permalink: pretty
