
url: http://brels.co.uk

# Site settings
title: 'Bright Electrical Specialists Ltd'
email: info@brels.co.uk
phone: '07775711145'
address1: '4 Cedar Road, Enfield'
address2: 'EN2 0TH'
disqus: 'brightelectricalspecialists'

description: 'Bright Electrical Specialists Ltd, based in Enfield,
    North London, carries out all types of electrical work within M25
    area, from a new plug socket to a complete or partial rewiring of
    your property professionally and efficiently. We are able to deal
    with any problem which may arise and undertake electrical test
    inspections, diagnostics and fault finding on electrical
    systems. All our work is carried out according to the British
    Standard BS 7671 (IEE) to meet electrical wiring regulations.'

# Color settings
color:
  primary: 'F7DB07'
  secondary: 'FFEE22'
  secondary-dark: '000000'

# Build settings
markdown: kramdown
permalink: pretty
